### ISSUE TITLE
Move comments details to non-normative section

### ISSUE THREAD

**Issue by nightwatchcyber** [nightwatchcybersecurity/rfc4180-bis#32]
Comments syntax isn't supported across all implementations, so we should move it to the non-normative section

**Comment by osiegmar** [comment]
Please see my comments and #33

**Comment by osiegmar** [comment]
After reviewing the current status, I didn't find any (real) gotchas. Just some comments (maybe minor improvements):

- The document sometimes uses "double-quote(s)" and sometimes "double quote(s)" (without a dash)
- The wording of sentance "1. Each record is located on a separate line, ended by a line break" seems to be in contrast to "6. Fields containing line breaks". Maybe just "1. Each record is ended by a line break" or "1. Each records starts on a separate line, ended by a line break"?
- While being totally fine with "2. The last record in the file MUST have an ending line break", I'm wondering what's the rationale behind this. In paragraph 4. there's this rationale "since this will indicate an empty field following the comma". Erroneous implementations could treat this last line break as a start of a new but empty record. Maybe also something for the "Common implementation concerns"?
- The sentance "(however, some programs do not use double quotes at all)" at paragraph 5 could be removed since there's now a dedicated section "Common implementation concerns" (with paragraph "Escaping double quotes").
- The paragraph "Fields spanning multiple lines" from section "Common implementation concerns" seems to be superfluous as this behaviour is part of the description / grammar.

**Comment by yakovsh** [comment]
>     * The document sometimes uses "double-quote(s)" and sometimes "double quote(s)" (without a dash)
> 

I will fix that and the RFC Editor will usually cleanup all similar grammar issues.

>     * The wording of sentence "1. Each record is located on a separate line, ended by a line break" seems to be in contrast to "6. Fields containing line breaks". Maybe just "1. Each record is ended by a line break" or "1. Each records starts on a separate line, ended by a line break"?

Going to leave this for now as per RFC4180.

> 
>     * While being totally fine with "2. The last record in the file MUST have an ending line break", I'm wondering what's the rationale behind this. In paragraph 4. there's this rationale "since this will indicate an empty field following the comma". Erroneous implementations could treat this last line break as a start of a new but empty record. Maybe also something for the "Common implementation concerns"?
> 

There was a concern raised that this is ambiguous. I might add something to the empty lines section.

>     * The sentence "(however, some programs do not use double quotes at all)" at paragraph 5 could be removed since there's now a dedicated section "Common implementation concerns" (with paragraph "Escaping double quotes").
> 

Ok

>     * The paragraph "Fields spanning multiple lines" from section "Common implementation concerns" seems to be superfluous as this behaviour is part of the description / grammar.

I wanted to call this out since this a common implementation problem.
